/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables.records;


import com.dq.DQTRM.model.tables.TmAdditionalStatement;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmAdditionalStatementRecord extends TableRecordImpl<TmAdditionalStatementRecord> implements Record9<String, String, Integer, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -557960117;

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.FK_TRADEMARK_GID</code>.
     */
    public void setFkTrademarkGid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.FK_TRADEMARK_GID</code>.
     */
    public String getFkTrademarkGid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.FK_STATEMENT_TYPE_CD</code>.
     */
    public void setFkStatementTypeCd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.FK_STATEMENT_TYPE_CD</code>.
     */
    public String getFkStatementTypeCd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.ORDER_NO</code>.
     */
    public void setOrderNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.ORDER_NO</code>.
     */
    public Integer getOrderNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.LOCK_CONTROL_NO</code>.
     */
    public void setLockControlNo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.LOCK_CONTROL_NO</code>.
     */
    public Integer getLockControlNo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.CREATE_TS</code>.
     */
    public void setCreateTs(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.CREATE_TS</code>.
     */
    public String getCreateTs() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.LAST_MOD_TS</code>.
     */
    public void setLastModTs(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.LAST_MOD_TS</code>.
     */
    public String getLastModTs() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.LAST_MOD_USER_ID</code>.
     */
    public void setLastModUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.LAST_MOD_USER_ID</code>.
     */
    public String getLastModUserId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.STATEMENT_TX</code>.
     */
    public void setStatementTx(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DQTRM.TM_ADDITIONAL_STATEMENT.STATEMENT_TX</code>.
     */
    public String getStatementTx() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Integer, Integer, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Integer, Integer, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.FK_TRADEMARK_GID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.FK_STATEMENT_TYPE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.LOCK_CONTROL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.CREATE_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.LAST_MOD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.LAST_MOD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TmAdditionalStatement.TM_ADDITIONAL_STATEMENT.STATEMENT_TX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFkTrademarkGid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFkStatementTypeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLockControlNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastModTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastModUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStatementTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value1(String value) {
        setFkTrademarkGid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value2(String value) {
        setFkStatementTypeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value3(Integer value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value4(Integer value) {
        setLockControlNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value5(String value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value6(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value7(String value) {
        setLastModTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value8(String value) {
        setLastModUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord value9(String value) {
        setStatementTx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatementRecord values(String value1, String value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmAdditionalStatementRecord
     */
    public TmAdditionalStatementRecord() {
        super(TmAdditionalStatement.TM_ADDITIONAL_STATEMENT);
    }

    /**
     * Create a detached, initialised TmAdditionalStatementRecord
     */
    public TmAdditionalStatementRecord(String fkTrademarkGid, String fkStatementTypeCd, Integer orderNo, Integer lockControlNo, String createTs, String createUserId, String lastModTs, String lastModUserId, String statementTx) {
        super(TmAdditionalStatement.TM_ADDITIONAL_STATEMENT);

        set(0, fkTrademarkGid);
        set(1, fkStatementTypeCd);
        set(2, orderNo);
        set(3, lockControlNo);
        set(4, createTs);
        set(5, createUserId);
        set(6, lastModTs);
        set(7, lastModUserId);
        set(8, statementTx);
    }
}
