/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables.records;


import com.dq.DQTRM.model.tables.TmDrawing;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDrawingRecord extends TableRecordImpl<TmDrawingRecord> implements Record9<String, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1508467936;

    /**
     * Setter for <code>DQTRM.TM_DRAWING.FK_TRADEMARK_GID</code>.
     */
    public void setFkTrademarkGid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.FK_TRADEMARK_GID</code>.
     */
    public String getFkTrademarkGid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.COLOR_IN</code>.
     */
    public void setColorIn(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.COLOR_IN</code>.
     */
    public String getColorIn() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.THREE_DIMENSION_IN</code>.
     */
    public void setThreeDimensionIn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.THREE_DIMENSION_IN</code>.
     */
    public String getThreeDimensionIn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.COLOR_CLAIM_TX</code>.
     */
    public void setColorClaimTx(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.COLOR_CLAIM_TX</code>.
     */
    public String getColorClaimTx() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.LOCK_CONTROL_NO</code>.
     */
    public void setLockControlNo(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.LOCK_CONTROL_NO</code>.
     */
    public Integer getLockControlNo() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.CREATE_TS</code>.
     */
    public void setCreateTs(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.CREATE_TS</code>.
     */
    public String getCreateTs() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.LAST_MOD_TS</code>.
     */
    public void setLastModTs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.LAST_MOD_TS</code>.
     */
    public String getLastModTs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DQTRM.TM_DRAWING.LAST_MOD_USER_ID</code>.
     */
    public void setLastModUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DQTRM.TM_DRAWING.LAST_MOD_USER_ID</code>.
     */
    public String getLastModUserId() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmDrawing.TM_DRAWING.FK_TRADEMARK_GID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmDrawing.TM_DRAWING.COLOR_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmDrawing.TM_DRAWING.THREE_DIMENSION_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TmDrawing.TM_DRAWING.COLOR_CLAIM_TX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TmDrawing.TM_DRAWING.LOCK_CONTROL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TmDrawing.TM_DRAWING.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TmDrawing.TM_DRAWING.CREATE_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TmDrawing.TM_DRAWING.LAST_MOD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TmDrawing.TM_DRAWING.LAST_MOD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFkTrademarkGid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getColorIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getThreeDimensionIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getColorClaimTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLockControlNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastModTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLastModUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value1(String value) {
        setFkTrademarkGid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value2(String value) {
        setColorIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value3(String value) {
        setThreeDimensionIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value4(String value) {
        setColorClaimTx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value5(Integer value) {
        setLockControlNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value6(String value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value7(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value8(String value) {
        setLastModTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord value9(String value) {
        setLastModUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDrawingRecord values(String value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmDrawingRecord
     */
    public TmDrawingRecord() {
        super(TmDrawing.TM_DRAWING);
    }

    /**
     * Create a detached, initialised TmDrawingRecord
     */
    public TmDrawingRecord(String fkTrademarkGid, String colorIn, String threeDimensionIn, String colorClaimTx, Integer lockControlNo, String createTs, String createUserId, String lastModTs, String lastModUserId) {
        super(TmDrawing.TM_DRAWING);

        set(0, fkTrademarkGid);
        set(1, colorIn);
        set(2, threeDimensionIn);
        set(3, colorClaimTx);
        set(4, lockControlNo);
        set(5, createTs);
        set(6, createUserId);
        set(7, lastModTs);
        set(8, lastModUserId);
    }
}
