/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables.records;


import com.dq.DQTRM.model.tables.TmEmployeeAssignment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmEmployeeAssignmentRecord extends TableRecordImpl<TmEmployeeAssignmentRecord> implements Record9<String, String, String, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -1132082237;

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.FK_TRADEMARK_GID</code>.
     */
    public void setFkTrademarkGid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.FK_TRADEMARK_GID</code>.
     */
    public String getFkTrademarkGid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.FK_TM_EMPLOYEE_ROLE_CD</code>.
     */
    public void setFkTmEmployeeRoleCd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.FK_TM_EMPLOYEE_ROLE_CD</code>.
     */
    public String getFkTmEmployeeRoleCd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CFK_EMPLOYEE_NO</code>.
     */
    public void setCfkEmployeeNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CFK_EMPLOYEE_NO</code>.
     */
    public String getCfkEmployeeNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LOCK_CONTROL_NO</code>.
     */
    public void setLockControlNo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LOCK_CONTROL_NO</code>.
     */
    public Integer getLockControlNo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CREATE_TS</code>.
     */
    public void setCreateTs(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CREATE_TS</code>.
     */
    public String getCreateTs() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_TS</code>.
     */
    public void setLastModTs(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_TS</code>.
     */
    public String getLastModTs() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_USER_ID</code>.
     */
    public void setLastModUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_USER_ID</code>.
     */
    public String getLastModUserId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.EFFECTIVE_DT</code>.
     */
    public void setEffectiveDt(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.EFFECTIVE_DT</code>.
     */
    public String getEffectiveDt() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Integer, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Integer, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.FK_TRADEMARK_GID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.FK_TM_EMPLOYEE_ROLE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.CFK_EMPLOYEE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.LOCK_CONTROL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.CREATE_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT.EFFECTIVE_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFkTrademarkGid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFkTmEmployeeRoleCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCfkEmployeeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLockControlNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastModTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastModUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEffectiveDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value1(String value) {
        setFkTrademarkGid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value2(String value) {
        setFkTmEmployeeRoleCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value3(String value) {
        setCfkEmployeeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value4(Integer value) {
        setLockControlNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value5(String value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value6(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value7(String value) {
        setLastModTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value8(String value) {
        setLastModUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord value9(String value) {
        setEffectiveDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignmentRecord values(String value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmEmployeeAssignmentRecord
     */
    public TmEmployeeAssignmentRecord() {
        super(TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT);
    }

    /**
     * Create a detached, initialised TmEmployeeAssignmentRecord
     */
    public TmEmployeeAssignmentRecord(String fkTrademarkGid, String fkTmEmployeeRoleCd, String cfkEmployeeNo, Integer lockControlNo, String createTs, String createUserId, String lastModTs, String lastModUserId, String effectiveDt) {
        super(TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT);

        set(0, fkTrademarkGid);
        set(1, fkTmEmployeeRoleCd);
        set(2, cfkEmployeeNo);
        set(3, lockControlNo);
        set(4, createTs);
        set(5, createUserId);
        set(6, lastModTs);
        set(7, lastModUserId);
        set(8, effectiveDt);
    }
}
