/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables.records;


import com.dq.DQTRM.model.tables.TmMarkType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMarkTypeRecord extends TableRecordImpl<TmMarkTypeRecord> implements Record7<String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 517319614;

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.FK_TRADEMARK_GID</code>.
     */
    public void setFkTrademarkGid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.FK_TRADEMARK_GID</code>.
     */
    public String getFkTrademarkGid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.FK_MARK_TYPE_CD</code>.
     */
    public void setFkMarkTypeCd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.FK_MARK_TYPE_CD</code>.
     */
    public String getFkMarkTypeCd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.LOCK_CONTROL_NO</code>.
     */
    public void setLockControlNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.LOCK_CONTROL_NO</code>.
     */
    public Integer getLockControlNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.CREATE_TS</code>.
     */
    public void setCreateTs(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.CREATE_TS</code>.
     */
    public String getCreateTs() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.LAST_MOD_TS</code>.
     */
    public void setLastModTs(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.LAST_MOD_TS</code>.
     */
    public String getLastModTs() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DQTRM.TM_MARK_TYPE.LAST_MOD_USER_ID</code>.
     */
    public void setLastModUserId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRM.TM_MARK_TYPE.LAST_MOD_USER_ID</code>.
     */
    public String getLastModUserId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmMarkType.TM_MARK_TYPE.FK_TRADEMARK_GID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TmMarkType.TM_MARK_TYPE.FK_MARK_TYPE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TmMarkType.TM_MARK_TYPE.LOCK_CONTROL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TmMarkType.TM_MARK_TYPE.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TmMarkType.TM_MARK_TYPE.CREATE_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TmMarkType.TM_MARK_TYPE.LAST_MOD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TmMarkType.TM_MARK_TYPE.LAST_MOD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFkTrademarkGid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFkMarkTypeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLockControlNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLastModTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastModUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value1(String value) {
        setFkTrademarkGid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value2(String value) {
        setFkMarkTypeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value3(Integer value) {
        setLockControlNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value4(String value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value5(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value6(String value) {
        setLastModTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord value7(String value) {
        setLastModUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkTypeRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmMarkTypeRecord
     */
    public TmMarkTypeRecord() {
        super(TmMarkType.TM_MARK_TYPE);
    }

    /**
     * Create a detached, initialised TmMarkTypeRecord
     */
    public TmMarkTypeRecord(String fkTrademarkGid, String fkMarkTypeCd, Integer lockControlNo, String createTs, String createUserId, String lastModTs, String lastModUserId) {
        super(TmMarkType.TM_MARK_TYPE);

        set(0, fkTrademarkGid);
        set(1, fkMarkTypeCd);
        set(2, lockControlNo);
        set(3, createTs);
        set(4, createUserId);
        set(5, lastModTs);
        set(6, lastModUserId);
    }
}
