/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables.records;


import com.dq.DQTRM.model.tables.TmRenewal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmRenewalRecord extends TableRecordImpl<TmRenewalRecord> implements Record10<String, Integer, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1005209135;

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.FK_TRADEMARK_GID</code>.
     */
    public void setFkTrademarkGid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.FK_TRADEMARK_GID</code>.
     */
    public String getFkTrademarkGid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.SEQUENCE_NO</code>.
     */
    public void setSequenceNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.SEQUENCE_NO</code>.
     */
    public Integer getSequenceNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.RENEWAL_FILED_DT</code>.
     */
    public void setRenewalFiledDt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.RENEWAL_FILED_DT</code>.
     */
    public String getRenewalFiledDt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.RENEWAL_BEGIN_EFFECTIVE_DT</code>.
     */
    public void setRenewalBeginEffectiveDt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.RENEWAL_BEGIN_EFFECTIVE_DT</code>.
     */
    public String getRenewalBeginEffectiveDt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.RENEWAL_END_EFFECTIVE_DT</code>.
     */
    public void setRenewalEndEffectiveDt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.RENEWAL_END_EFFECTIVE_DT</code>.
     */
    public String getRenewalEndEffectiveDt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.LOCK_CONTROL_NO</code>.
     */
    public void setLockControlNo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.LOCK_CONTROL_NO</code>.
     */
    public Integer getLockControlNo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.CREATE_TS</code>.
     */
    public void setCreateTs(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.CREATE_TS</code>.
     */
    public String getCreateTs() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.LAST_MOD_TS</code>.
     */
    public void setLastModTs(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.LAST_MOD_TS</code>.
     */
    public String getLastModTs() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DQTRM.TM_RENEWAL.LAST_MOD_USER_ID</code>.
     */
    public void setLastModUserId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>DQTRM.TM_RENEWAL.LAST_MOD_USER_ID</code>.
     */
    public String getLastModUserId() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Integer, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Integer, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TmRenewal.TM_RENEWAL.FK_TRADEMARK_GID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TmRenewal.TM_RENEWAL.SEQUENCE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TmRenewal.TM_RENEWAL.RENEWAL_FILED_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TmRenewal.TM_RENEWAL.RENEWAL_BEGIN_EFFECTIVE_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TmRenewal.TM_RENEWAL.RENEWAL_END_EFFECTIVE_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TmRenewal.TM_RENEWAL.LOCK_CONTROL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TmRenewal.TM_RENEWAL.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TmRenewal.TM_RENEWAL.CREATE_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TmRenewal.TM_RENEWAL.LAST_MOD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TmRenewal.TM_RENEWAL.LAST_MOD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFkTrademarkGid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSequenceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRenewalFiledDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRenewalBeginEffectiveDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRenewalEndEffectiveDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLockControlNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLastModTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastModUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value1(String value) {
        setFkTrademarkGid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value2(Integer value) {
        setSequenceNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value3(String value) {
        setRenewalFiledDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value4(String value) {
        setRenewalBeginEffectiveDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value5(String value) {
        setRenewalEndEffectiveDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value6(Integer value) {
        setLockControlNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value7(String value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value8(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value9(String value) {
        setLastModTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord value10(String value) {
        setLastModUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewalRecord values(String value1, Integer value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TmRenewalRecord
     */
    public TmRenewalRecord() {
        super(TmRenewal.TM_RENEWAL);
    }

    /**
     * Create a detached, initialised TmRenewalRecord
     */
    public TmRenewalRecord(String fkTrademarkGid, Integer sequenceNo, String renewalFiledDt, String renewalBeginEffectiveDt, String renewalEndEffectiveDt, Integer lockControlNo, String createTs, String createUserId, String lastModTs, String lastModUserId) {
        super(TmRenewal.TM_RENEWAL);

        set(0, fkTrademarkGid);
        set(1, sequenceNo);
        set(2, renewalFiledDt);
        set(3, renewalBeginEffectiveDt);
        set(4, renewalEndEffectiveDt);
        set(5, lockControlNo);
        set(6, createTs);
        set(7, createUserId);
        set(8, lastModTs);
        set(9, lastModUserId);
    }
}
