/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables.records;


import com.dq.DQTRM.model.tables.Trademark;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrademarkRecord extends TableRecordImpl<TrademarkRecord> implements Record21<String, String, String, String, Integer, String, String, String, String, String, String, String, Integer, Integer, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1234299674;

    /**
     * Setter for <code>DQTRM.TRADEMARK.TRADEMARK_GID</code>.
     */
    public void setTrademarkGid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.TRADEMARK_GID</code>.
     */
    public String getTrademarkGid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.FK_MARK_DRAWING_TYPE_CD</code>.
     */
    public void setFkMarkDrawingTypeCd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.FK_MARK_DRAWING_TYPE_CD</code>.
     */
    public String getFkMarkDrawingTypeCd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.FK_FEE_PROCESS_TYPE_CD</code>.
     */
    public void setFkFeeProcessTypeCd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.FK_FEE_PROCESS_TYPE_CD</code>.
     */
    public String getFkFeeProcessTypeCd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.SERIAL_NUM_TX</code>.
     */
    public void setSerialNumTx(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.SERIAL_NUM_TX</code>.
     */
    public String getSerialNumTx() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.REGISTRATION_NUM</code>.
     */
    public void setRegistrationNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.REGISTRATION_NUM</code>.
     */
    public Integer getRegistrationNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.FILING_DT</code>.
     */
    public void setFilingDt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.FILING_DT</code>.
     */
    public String getFilingDt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.REGISTRY_CT</code>.
     */
    public void setRegistryCt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.REGISTRY_CT</code>.
     */
    public String getRegistryCt() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.STANDARD_CHARACTER_TX</code>.
     */
    public void setStandardCharacterTx(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.STANDARD_CHARACTER_TX</code>.
     */
    public String getStandardCharacterTx() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.MARK_DESCRIPTION_TX</code>.
     */
    public void setMarkDescriptionTx(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.MARK_DESCRIPTION_TX</code>.
     */
    public String getMarkDescriptionTx() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.PREFERRED_CONTACT_METHOD_CT</code>.
     */
    public void setPreferredContactMethodCt(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.PREFERRED_CONTACT_METHOD_CT</code>.
     */
    public String getPreferredContactMethodCt() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.EFFECTIVE_FILING_DT</code>.
     */
    public void setEffectiveFilingDt(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.EFFECTIVE_FILING_DT</code>.
     */
    public String getEffectiveFilingDt() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.COLLECTIVE_IN</code>.
     */
    public void setCollectiveIn(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.COLLECTIVE_IN</code>.
     */
    public String getCollectiveIn() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.LEGACY_STATUS_CD</code>.
     */
    public void setLegacyStatusCd(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.LEGACY_STATUS_CD</code>.
     */
    public Integer getLegacyStatusCd() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.LOCK_CONTROL_NO</code>.
     */
    public void setLockControlNo(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.LOCK_CONTROL_NO</code>.
     */
    public Integer getLockControlNo() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.CREATE_TS</code>.
     */
    public void setCreateTs(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.CREATE_TS</code>.
     */
    public String getCreateTs() {
        return (String) get(14);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.LAST_MOD_TS</code>.
     */
    public void setLastModTs(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.LAST_MOD_TS</code>.
     */
    public String getLastModTs() {
        return (String) get(16);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.LAST_MOD_USER_ID</code>.
     */
    public void setLastModUserId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.LAST_MOD_USER_ID</code>.
     */
    public String getLastModUserId() {
        return (String) get(17);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.STATUS_DT</code>.
     */
    public void setStatusDt(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.STATUS_DT</code>.
     */
    public String getStatusDt() {
        return (String) get(18);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.LAST_ACTION_DT</code>.
     */
    public void setLastActionDt(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.LAST_ACTION_DT</code>.
     */
    public String getLastActionDt() {
        return (String) get(19);
    }

    /**
     * Setter for <code>DQTRM.TRADEMARK.AVAILABLE_FOR_SOU_IN</code>.
     */
    public void setAvailableForSouIn(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>DQTRM.TRADEMARK.AVAILABLE_FOR_SOU_IN</code>.
     */
    public String getAvailableForSouIn() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<String, String, String, String, Integer, String, String, String, String, String, String, String, Integer, Integer, String, String, String, String, String, String, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<String, String, String, String, Integer, String, String, String, String, String, String, String, Integer, Integer, String, String, String, String, String, String, String> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Trademark.TRADEMARK.TRADEMARK_GID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Trademark.TRADEMARK.FK_MARK_DRAWING_TYPE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Trademark.TRADEMARK.FK_FEE_PROCESS_TYPE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Trademark.TRADEMARK.SERIAL_NUM_TX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Trademark.TRADEMARK.REGISTRATION_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Trademark.TRADEMARK.FILING_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Trademark.TRADEMARK.REGISTRY_CT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Trademark.TRADEMARK.STANDARD_CHARACTER_TX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Trademark.TRADEMARK.MARK_DESCRIPTION_TX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Trademark.TRADEMARK.PREFERRED_CONTACT_METHOD_CT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Trademark.TRADEMARK.EFFECTIVE_FILING_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Trademark.TRADEMARK.COLLECTIVE_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Trademark.TRADEMARK.LEGACY_STATUS_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Trademark.TRADEMARK.LOCK_CONTROL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Trademark.TRADEMARK.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Trademark.TRADEMARK.CREATE_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Trademark.TRADEMARK.LAST_MOD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Trademark.TRADEMARK.LAST_MOD_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Trademark.TRADEMARK.STATUS_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return Trademark.TRADEMARK.LAST_ACTION_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return Trademark.TRADEMARK.AVAILABLE_FOR_SOU_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTrademarkGid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFkMarkDrawingTypeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFkFeeProcessTypeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSerialNumTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRegistrationNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFilingDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRegistryCt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStandardCharacterTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getMarkDescriptionTx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPreferredContactMethodCt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getEffectiveFilingDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCollectiveIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getLegacyStatusCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getLockControlNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getLastModTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getLastModUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getStatusDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getLastActionDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getAvailableForSouIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value1(String value) {
        setTrademarkGid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value2(String value) {
        setFkMarkDrawingTypeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value3(String value) {
        setFkFeeProcessTypeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value4(String value) {
        setSerialNumTx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value5(Integer value) {
        setRegistrationNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value6(String value) {
        setFilingDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value7(String value) {
        setRegistryCt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value8(String value) {
        setStandardCharacterTx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value9(String value) {
        setMarkDescriptionTx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value10(String value) {
        setPreferredContactMethodCt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value11(String value) {
        setEffectiveFilingDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value12(String value) {
        setCollectiveIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value13(Integer value) {
        setLegacyStatusCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value14(Integer value) {
        setLockControlNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value15(String value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value16(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value17(String value) {
        setLastModTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value18(String value) {
        setLastModUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value19(String value) {
        setStatusDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value20(String value) {
        setLastActionDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord value21(String value) {
        setAvailableForSouIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrademarkRecord values(String value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13, Integer value14, String value15, String value16, String value17, String value18, String value19, String value20, String value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrademarkRecord
     */
    public TrademarkRecord() {
        super(Trademark.TRADEMARK);
    }

    /**
     * Create a detached, initialised TrademarkRecord
     */
    public TrademarkRecord(String trademarkGid, String fkMarkDrawingTypeCd, String fkFeeProcessTypeCd, String serialNumTx, Integer registrationNum, String filingDt, String registryCt, String standardCharacterTx, String markDescriptionTx, String preferredContactMethodCt, String effectiveFilingDt, String collectiveIn, Integer legacyStatusCd, Integer lockControlNo, String createTs, String createUserId, String lastModTs, String lastModUserId, String statusDt, String lastActionDt, String availableForSouIn) {
        super(Trademark.TRADEMARK);

        set(0, trademarkGid);
        set(1, fkMarkDrawingTypeCd);
        set(2, fkFeeProcessTypeCd);
        set(3, serialNumTx);
        set(4, registrationNum);
        set(5, filingDt);
        set(6, registryCt);
        set(7, standardCharacterTx);
        set(8, markDescriptionTx);
        set(9, preferredContactMethodCt);
        set(10, effectiveFilingDt);
        set(11, collectiveIn);
        set(12, legacyStatusCd);
        set(13, lockControlNo);
        set(14, createTs);
        set(15, createUserId);
        set(16, lastModTs);
        set(17, lastModUserId);
        set(18, statusDt);
        set(19, lastActionDt);
        set(20, availableForSouIn);
    }
}
