/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRAM.model;


import com.dq.DQTRAM.model.tables.TramAm;
import com.dq.DQTRAM.model.tables.TramPr;
import com.dq.DQTRAM.model.tables.TramPx;
import com.dq.DQTRAM.model.tables.TramWp;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in DQTRAM
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DQTRAM.TRAM_AM</code>.
     */
    public static final TramAm TRAM_AM = com.dq.DQTRAM.model.tables.TramAm.TRAM_AM;

    /**
     * The table <code>DQTRAM.TRAM_PR</code>.
     */
    public static final TramPr TRAM_PR = com.dq.DQTRAM.model.tables.TramPr.TRAM_PR;

    /**
     * The table <code>DQTRAM.TRAM_PX</code>.
     */
    public static final TramPx TRAM_PX = com.dq.DQTRAM.model.tables.TramPx.TRAM_PX;

    /**
     * The table <code>DQTRAM.TRAM_WP</code>.
     */
    public static final TramWp TRAM_WP = com.dq.DQTRAM.model.tables.TramWp.TRAM_WP;
}
