/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRAM.model.tables.records;


import com.dq.DQTRAM.model.tables.TramPx;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TramPxRecord extends TableRecordImpl<TramPxRecord> implements Record10<Integer, Integer, Integer, String, String, String, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -913651030;

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_DT_CREATED</code>.
     */
    public void setPxDtCreated(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_DT_CREATED</code>.
     */
    public Integer getPxDtCreated() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_DT_EXT</code>.
     */
    public void setPxDtExt(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_DT_EXT</code>.
     */
    public Integer getPxDtExt() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_ENT_NUM</code>.
     */
    public void setPxEntNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_ENT_NUM</code>.
     */
    public Integer getPxEntNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_FORM_TYPE</code>.
     */
    public void setPxFormType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_FORM_TYPE</code>.
     */
    public String getPxFormType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_PRGRPH_TYPE</code>.
     */
    public void setPxPrgrphType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_PRGRPH_TYPE</code>.
     */
    public String getPxPrgrphType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_PRINT_LINE</code>.
     */
    public void setPxPrintLine(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_PRINT_LINE</code>.
     */
    public String getPxPrintLine() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_REG_NUM</code>.
     */
    public void setPxRegNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_REG_NUM</code>.
     */
    public Integer getPxRegNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_SER_NUM</code>.
     */
    public void setPxSerNum(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_SER_NUM</code>.
     */
    public Integer getPxSerNum() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_STAT_CD</code>.
     */
    public void setPxStatCd(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_STAT_CD</code>.
     */
    public String getPxStatCd() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PX.PX_RSN</code>.
     */
    public void setPxRsn(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PX.PX_RSN</code>.
     */
    public Integer getPxRsn() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, String, Integer, Integer, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, String, Integer, Integer, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TramPx.TRAM_PX.PX_DT_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TramPx.TRAM_PX.PX_DT_EXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TramPx.TRAM_PX.PX_ENT_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TramPx.TRAM_PX.PX_FORM_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TramPx.TRAM_PX.PX_PRGRPH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TramPx.TRAM_PX.PX_PRINT_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TramPx.TRAM_PX.PX_REG_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TramPx.TRAM_PX.PX_SER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TramPx.TRAM_PX.PX_STAT_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return TramPx.TRAM_PX.PX_RSN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPxDtCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPxDtExt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPxEntNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPxFormType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPxPrgrphType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPxPrintLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPxRegNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPxSerNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPxStatCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPxRsn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value1(Integer value) {
        setPxDtCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value2(Integer value) {
        setPxDtExt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value3(Integer value) {
        setPxEntNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value4(String value) {
        setPxFormType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value5(String value) {
        setPxPrgrphType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value6(String value) {
        setPxPrintLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value7(Integer value) {
        setPxRegNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value8(Integer value) {
        setPxSerNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value9(String value) {
        setPxStatCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord value10(Integer value) {
        setPxRsn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPxRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, Integer value7, Integer value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TramPxRecord
     */
    public TramPxRecord() {
        super(TramPx.TRAM_PX);
    }

    /**
     * Create a detached, initialised TramPxRecord
     */
    public TramPxRecord(Integer pxDtCreated, Integer pxDtExt, Integer pxEntNum, String pxFormType, String pxPrgrphType, String pxPrintLine, Integer pxRegNum, Integer pxSerNum, String pxStatCd, Integer pxRsn) {
        super(TramPx.TRAM_PX);

        set(0, pxDtCreated);
        set(1, pxDtExt);
        set(2, pxEntNum);
        set(3, pxFormType);
        set(4, pxPrgrphType);
        set(5, pxPrintLine);
        set(6, pxRegNum);
        set(7, pxSerNum);
        set(8, pxStatCd);
        set(9, pxRsn);
    }
}
