/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRAM.model.tables.records;


import com.dq.DQTRAM.model.tables.TramPr;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TramPrRecord extends TableRecordImpl<TramPrRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -877289477;

    /**
     * Setter for <code>DQTRAM.TRAM_PR.PR_RCD_TYPE</code>.
     */
    public void setPrRcdType(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PR.PR_RCD_TYPE</code>.
     */
    public Integer getPrRcdType() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PR.PR_REL_ID_NUM</code>.
     */
    public void setPrRelIdNum(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PR.PR_REL_ID_NUM</code>.
     */
    public String getPrRelIdNum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PR.PR_SER_NUM</code>.
     */
    public void setPrSerNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PR.PR_SER_NUM</code>.
     */
    public Integer getPrSerNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DQTRAM.TRAM_PR.PR_RSN</code>.
     */
    public void setPrRsn(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DQTRAM.TRAM_PR.PR_RSN</code>.
     */
    public Integer getPrRsn() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TramPr.TRAM_PR.PR_RCD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TramPr.TRAM_PR.PR_REL_ID_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TramPr.TRAM_PR.PR_SER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TramPr.TRAM_PR.PR_RSN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPrRcdType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrRelIdNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPrSerNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrRsn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPrRecord value1(Integer value) {
        setPrRcdType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPrRecord value2(String value) {
        setPrRelIdNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPrRecord value3(Integer value) {
        setPrSerNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPrRecord value4(Integer value) {
        setPrRsn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPrRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TramPrRecord
     */
    public TramPrRecord() {
        super(TramPr.TRAM_PR);
    }

    /**
     * Create a detached, initialised TramPrRecord
     */
    public TramPrRecord(Integer prRcdType, String prRelIdNum, Integer prSerNum, Integer prRsn) {
        super(TramPr.TRAM_PR);

        set(0, prRcdType);
        set(1, prRelIdNum);
        set(2, prSerNum);
        set(3, prRsn);
    }
}
