/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRAM.model.tables;


import com.dq.DQTRAM.model.Dqtram;
import com.dq.DQTRAM.model.tables.records.TramPxRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TramPx extends TableImpl<TramPxRecord> {

    private static final long serialVersionUID = -514754662;

    /**
     * The reference instance of <code>DQTRAM.TRAM_PX</code>
     */
    public static final TramPx TRAM_PX = new TramPx();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TramPxRecord> getRecordType() {
        return TramPxRecord.class;
    }

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_DT_CREATED</code>.
     */
    public final TableField<TramPxRecord, Integer> PX_DT_CREATED = createField("PX_DT_CREATED", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_DT_EXT</code>.
     */
    public final TableField<TramPxRecord, Integer> PX_DT_EXT = createField("PX_DT_EXT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_ENT_NUM</code>.
     */
    public final TableField<TramPxRecord, Integer> PX_ENT_NUM = createField("PX_ENT_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_FORM_TYPE</code>.
     */
    public final TableField<TramPxRecord, String> PX_FORM_TYPE = createField("PX_FORM_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(4).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_PRGRPH_TYPE</code>.
     */
    public final TableField<TramPxRecord, String> PX_PRGRPH_TYPE = createField("PX_PRGRPH_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(5).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_PRINT_LINE</code>.
     */
    public final TableField<TramPxRecord, String> PX_PRINT_LINE = createField("PX_PRINT_LINE", org.jooq.impl.SQLDataType.VARCHAR.length(75).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_REG_NUM</code>.
     */
    public final TableField<TramPxRecord, Integer> PX_REG_NUM = createField("PX_REG_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_SER_NUM</code>.
     */
    public final TableField<TramPxRecord, Integer> PX_SER_NUM = createField("PX_SER_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_STAT_CD</code>.
     */
    public final TableField<TramPxRecord, String> PX_STAT_CD = createField("PX_STAT_CD", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PX.PX_RSN</code>.
     */
    public final TableField<TramPxRecord, Integer> PX_RSN = createField("PX_RSN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>DQTRAM.TRAM_PX</code> table reference
     */
    public TramPx() {
        this("TRAM_PX", null);
    }

    /**
     * Create an aliased <code>DQTRAM.TRAM_PX</code> table reference
     */
    public TramPx(String alias) {
        this(alias, TRAM_PX);
    }

    private TramPx(String alias, Table<TramPxRecord> aliased) {
        this(alias, aliased, null);
    }

    private TramPx(String alias, Table<TramPxRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtram.DQTRAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPx as(String alias) {
        return new TramPx(alias, this);
    }

    /**
     * Rename this table
     */
    public TramPx rename(String name) {
        return new TramPx(name, null);
    }
}
