/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRAM.model.tables;


import com.dq.DQTRAM.model.Dqtram;
import com.dq.DQTRAM.model.tables.records.TramPrRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TramPr extends TableImpl<TramPrRecord> {

    private static final long serialVersionUID = -1450554695;

    /**
     * The reference instance of <code>DQTRAM.TRAM_PR</code>
     */
    public static final TramPr TRAM_PR = new TramPr();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TramPrRecord> getRecordType() {
        return TramPrRecord.class;
    }

    /**
     * The column <code>DQTRAM.TRAM_PR.PR_RCD_TYPE</code>.
     */
    public final TableField<TramPrRecord, Integer> PR_RCD_TYPE = createField("PR_RCD_TYPE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PR.PR_REL_ID_NUM</code>.
     */
    public final TableField<TramPrRecord, String> PR_REL_ID_NUM = createField("PR_REL_ID_NUM", org.jooq.impl.SQLDataType.VARCHAR.length(8).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PR.PR_SER_NUM</code>.
     */
    public final TableField<TramPrRecord, Integer> PR_SER_NUM = createField("PR_SER_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_PR.PR_RSN</code>.
     */
    public final TableField<TramPrRecord, Integer> PR_RSN = createField("PR_RSN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>DQTRAM.TRAM_PR</code> table reference
     */
    public TramPr() {
        this("TRAM_PR", null);
    }

    /**
     * Create an aliased <code>DQTRAM.TRAM_PR</code> table reference
     */
    public TramPr(String alias) {
        this(alias, TRAM_PR);
    }

    private TramPr(String alias, Table<TramPrRecord> aliased) {
        this(alias, aliased, null);
    }

    private TramPr(String alias, Table<TramPrRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtram.DQTRAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramPr as(String alias) {
        return new TramPr(alias, this);
    }

    /**
     * Rename this table
     */
    public TramPr rename(String name) {
        return new TramPr(name, null);
    }
}
