/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRAM.model.tables;


import com.dq.DQTRAM.model.Dqtram;
import com.dq.DQTRAM.model.tables.records.TramAmRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TramAm extends TableImpl<TramAmRecord> {

    private static final long serialVersionUID = -115994182;

    /**
     * The reference instance of <code>DQTRAM.TRAM_AM</code>
     */
    public static final TramAm TRAM_AM = new TramAm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TramAmRecord> getRecordType() {
        return TramAmRecord.class;
    }

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ADDR_1</code>.
     */
    public final TableField<TramAmRecord, String> AM_ADDR_1 = createField("AM_ADDR_1", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ADDR_2</code>.
     */
    public final TableField<TramAmRecord, String> AM_ADDR_2 = createField("AM_ADDR_2", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ADDR_3</code>.
     */
    public final TableField<TramAmRecord, String> AM_ADDR_3 = createField("AM_ADDR_3", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ADDR_4</code>.
     */
    public final TableField<TramAmRecord, String> AM_ADDR_4 = createField("AM_ADDR_4", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ADDR_5</code>.
     */
    public final TableField<TramAmRecord, String> AM_ADDR_5 = createField("AM_ADDR_5", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_BTCH_NUM</code>.
     */
    public final TableField<TramAmRecord, String> AM_BTCH_NUM = createField("AM_BTCH_NUM", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_CNCL_CD</code>.
     */
    public final TableField<TramAmRecord, String> AM_CNCL_CD = createField("AM_CNCL_CD", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_CHRG_TO</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_CHRG_TO = createField("AM_CHRG_TO", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_CHRG_TO_LOC</code>.
     */
    public final TableField<TramAmRecord, String> AM_CHRG_TO_LOC = createField("AM_CHRG_TO_LOC", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_CLS_CT_ACTV</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_CLS_CT_ACTV = createField("AM_CLS_CT_ACTV", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_ABAN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_ABAN = createField("AM_DT_ABAN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_AMND_REG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_AMND_REG = createField("AM_DT_AMND_REG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_CNCL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_CNCL = createField("AM_DT_CNCL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_FIL = createField("AM_DT_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_PUB</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_PUB = createField("AM_DT_PUB", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_PUB_12C</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_PUB_12C = createField("AM_DT_PUB_12C", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_REG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_REG = createField("AM_DT_REG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_RNWL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_RNWL = createField("AM_DT_RNWL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LO_ASGN</code>.
     */
    public final TableField<TramAmRecord, String> AM_LO_ASGN = createField("AM_LO_ASGN", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_EXMR_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_EXMR_NUM = createField("AM_EXMR_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LDGR_QTY</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_LDGR_QTY = createField("AM_LDGR_QTY", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LOC</code>.
     */
    public final TableField<TramAmRecord, String> AM_LOC = createField("AM_LOC", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_MARK_1_LIN</code>.
     */
    public final TableField<TramAmRecord, String> AM_MARK_1_LIN = createField("AM_MARK_1_LIN", org.jooq.impl.SQLDataType.VARCHAR.length(40).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_MARK_DWG_CD</code>.
     */
    public final TableField<TramAmRecord, String> AM_MARK_DWG_CD = createField("AM_MARK_DWG_CD", org.jooq.impl.SQLDataType.VARCHAR.length(4).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_PARA_LGL_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_PARA_LGL_NUM = createField("AM_PARA_LGL_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_REG_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_REG_NUM = createField("AM_REG_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_SER_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_SER_NUM = createField("AM_SER_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_STE_CD_APPL</code>.
     */
    public final TableField<TramAmRecord, String> AM_STE_CD_APPL = createField("AM_STE_CD_APPL", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_STE_CD_REG</code>.
     */
    public final TableField<TramAmRecord, String> AM_STE_CD_REG = createField("AM_STE_CD_REG", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_STAT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_STAT = createField("AM_STAT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_TOT_CASE_ACT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_TOT_CASE_ACT = createField("AM_TOT_CASE_ACT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_TOT_PARA_ACT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_TOT_PARA_ACT = createField("AM_TOT_PARA_ACT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ADD_CASE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ADD_CASE = createField("AM_FLG_ADD_CASE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_AMND_APPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_AMND_APPL = createField("AM_FLG_AMND_APPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_AMND_PRIN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_AMND_PRIN = createField("AM_FLG_AMND_PRIN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_AMND_SUPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_AMND_SUPL = createField("AM_FLG_AMND_SUPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_AND_OTH_CD</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_AND_OTH_CD = createField("AM_FLG_AND_OTH_CD", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_APPEAL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_APPEAL = createField("AM_FLG_APPEAL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ASGT_RCD</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ASGT_RCD = createField("AM_FLG_ASGT_RCD", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_CHNG_REG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_CHNG_REG = createField("AM_FLG_CHNG_REG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_CNCL_PEND</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_CNCL_PEND = createField("AM_FLG_CNCL_PEND", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_CNCR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_CNCR = createField("AM_FLG_CNCR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_CNCR_PEND</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_CNCR_PEND = createField("AM_FLG_CNCR_PEND", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_DSPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_DSPL = createField("AM_FLG_DSPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_DIVD_CHLD</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_DIVD_CHLD = createField("AM_FLG_DIVD_CHLD", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_DIVD_PRNT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_DIVD_PRNT = createField("AM_FLG_DIVD_PRNT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_1_ACT_CT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_1_ACT_CT = createField("AM_FLG_1_ACT_CT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_1_ACT_MLG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_1_ACT_MLG = createField("AM_FLG_1_ACT_MLG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_1_ACT_PARA</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_1_ACT_PARA = createField("AM_FLG_1_ACT_PARA", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FRGN_DATA</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FRGN_DATA = createField("AM_FLG_FRGN_DATA", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FRPR_CLMD</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FRPR_CLMD = createField("AM_FLG_FRPR_CLMD", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_INACTV</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_INACTV = createField("AM_FLG_INACTV", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_INTF_PEND</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_INTF_PEND = createField("AM_FLG_INTF_PEND", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_MARK_OFLW</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_MARK_OFLW = createField("AM_FLG_MARK_OFLW", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TM = createField("AM_FLG_TM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_COLL_TM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_COLL_TM = createField("AM_FLG_COLL_TM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SM = createField("AM_FLG_SM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_COLL_SM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_COLL_SM = createField("AM_FLG_COLL_SM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_COLL_MM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_COLL_MM = createField("AM_FLG_COLL_MM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_CM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_CM = createField("AM_FLG_CM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NO_ACED</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NO_ACED = createField("AM_FLG_NO_ACED", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OFFL_SRCH</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OFFL_SRCH = createField("AM_FLG_OFFL_SRCH", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OPC_PRCS</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OPC_PRCS = createField("AM_FLG_OPC_PRCS", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OPPS_PEND</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OPPS_PEND = createField("AM_FLG_OPPS_PEND", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ORD_WHS</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ORD_WHS = createField("AM_FLG_ORD_WHS", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_HEAR_TTAB</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_HEAR_TTAB = createField("AM_FLG_HEAR_TTAB", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SPEC_GRNT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SPEC_GRNT = createField("AM_FLG_SPEC_GRNT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_POST_PRIN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_POST_PRIN = createField("AM_FLG_POST_PRIN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_POST_SUPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_POST_SUPL = createField("AM_FLG_POST_SUPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PRE_EXM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PRE_EXM = createField("AM_FLG_PRE_EXM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PUB_CNCR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PUB_CNCR = createField("AM_FLG_PUB_CNCR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PUB_INTF</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PUB_INTF = createField("AM_FLG_PUB_INTF", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_REF_1</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_REF_1 = createField("AM_FLG_REF_1", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_RNWL_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_RNWL_FIL = createField("AM_FLG_RNWL_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_RPB_SCT_12</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_RPB_SCT_12 = createField("AM_FLG_RPB_SCT_12", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_2F</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_2F = createField("AM_FLG_SCT_2F", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_2F_PT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_2F_PT = createField("AM_FLG_SCT_2F_PT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_8_ACPT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_8_ACPT = createField("AM_FLG_SCT_8_ACPT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_8_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_8_FIL = createField("AM_FLG_SCT_8_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_8_P_A</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_8_P_A = createField("AM_FLG_SCT_8_P_A", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_15_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_15_FIL = createField("AM_FLG_SCT_15_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_15_ACK</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_15_ACK = createField("AM_FLG_SCT_15_ACK", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SN_VERIFY</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SN_VERIFY = createField("AM_FLG_SN_VERIFY", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SUPL_REG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SUPL_REG = createField("AM_FLG_SUPL_REG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TTAB_DCSN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TTAB_DCSN = createField("AM_FLG_TTAB_DCSN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_UN_ANS_PET</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_UN_ANS_PET = createField("AM_FLG_UN_ANS_PET", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PAPER_RCV</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PAPER_RCV = createField("AM_FLG_PAPER_RCV", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ACTION</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ACTION = createField("AM_FLG_ACTION", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_BTCH_RPT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_BTCH_RPT = createField("AM_FLG_BTCH_RPT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_DEL_SN_REC</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_DEL_SN_REC = createField("AM_FLG_DEL_SN_REC", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NW_ISS_CS</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NW_ISS_CS = createField("AM_FLG_NW_ISS_CS", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_LOS_CASE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_LOS_CASE = createField("AM_FLG_LOS_CASE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_CERT_RE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_CERT_RE = createField("AM_FLG_CERT_RE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_DB_DUMP</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_DB_DUMP = createField("AM_FLG_DB_DUMP", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_CT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_CT = createField("AM_FLG_ITU_CT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_DSPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_DSPL = createField("AM_FLG_ITU_DSPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PRT_NOA</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PRT_NOA = createField("AM_FLG_PRT_NOA", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FIL_RCPT_C</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FIL_RCPT_C = createField("AM_FLG_FIL_RCPT_C", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FIL_RCPT_D</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FIL_RCPT_D = createField("AM_FLG_FIL_RCPT_D", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FIL_RCPT_O</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FIL_RCPT_O = createField("AM_FLG_FIL_RCPT_O", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FND_CASE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FND_CASE = createField("AM_FLG_FND_CASE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FUL_FIL_PR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FUL_FIL_PR = createField("AM_FLG_FUL_FIL_PR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_JKT_LBL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_JKT_LBL = createField("AM_FLG_JKT_LBL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOP</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOP = createField("AM_FLG_NOP", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOP_CRCT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOP_CRCT = createField("AM_FLG_NOP_CRCT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOR_SUPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOR_SUPL = createField("AM_FLG_NOR_SUPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOR_CRCT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOR_CRCT = createField("AM_FLG_NOR_CRCT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOT_ABAN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOT_ABAN = createField("AM_FLG_NOT_ABAN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG = createField("AM_FLG_OG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_AMND</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_AMND = createField("AM_FLG_OG_AMND", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_CNCL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_CNCL = createField("AM_FLG_OG_CNCL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_COC</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_COC = createField("AM_FLG_OG_COC", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_NW_CERT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_NW_CERT = createField("AM_FLG_OG_NW_CERT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_ORD</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_ORD = createField("AM_FLG_OG_ORD", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_PUB_EXT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_PUB_EXT = createField("AM_FLG_OG_PUB_EXT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_REG_EXT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_REG_EXT = createField("AM_FLG_OG_REG_EXT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_RNWL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_RNWL = createField("AM_FLG_OG_RNWL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_OG_RPUB</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_OG_RPUB = createField("AM_FLG_OG_RPUB", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PROL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PROL = createField("AM_FLG_PROL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PRTD_BVR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PRTD_BVR = createField("AM_FLG_PRTD_BVR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PX_BTCH</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PX_BTCH = createField("AM_FLG_PX_BTCH", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SRCH_RPT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SRCH_RPT = createField("AM_FLG_SRCH_RPT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PRNT_TF</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PRNT_TF = createField("AM_FLG_PRNT_TF", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_QR_CASE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_QR_CASE = createField("AM_FLG_QR_CASE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_ANA</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_ANA = createField("AM_FLG_ITU_ANA", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_CUR = createField("AM_FLG_ITU_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_FIL = createField("AM_FLG_ITU_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_PUBO</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_PUBO = createField("AM_FLG_ITU_PUBO", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ATTY_DKT_NUM</code>.
     */
    public final TableField<TramAmRecord, String> AM_ATTY_DKT_NUM = createField("AM_ATTY_DKT_NUM", org.jooq.impl.SQLDataType.VARCHAR.length(12).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_PHYC_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_PHYC_FIL = createField("AM_DT_PHYC_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_NOA_CD</code>.
     */
    public final TableField<TramAmRecord, String> AM_NOA_CD = createField("AM_NOA_CD", org.jooq.impl.SQLDataType.VARCHAR.length(1).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_EXT_LTR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_EXT_LTR = createField("AM_FLG_EXT_LTR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NIAR_LBL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NIAR_LBL = createField("AM_FLG_NIAR_LBL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_1</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_1 = createField("AM_FLG_1", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_2</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_2 = createField("AM_FLG_2", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TM_LBL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TM_LBL = createField("AM_FLG_TM_LBL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_USE_LTR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_USE_LTR = createField("AM_FLG_USE_LTR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_AF</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_AF = createField("AM_FLG_ITU_AF", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_DLP</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_DLP = createField("AM_FLG_ITU_DLP", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_EF</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_EF = createField("AM_FLG_ITU_EF", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_ILM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_ILM = createField("AM_FLG_ITU_ILM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_IRR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_IRR = createField("AM_FLG_ITU_IRR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_PC</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_PC = createField("AM_FLG_ITU_PC", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_UTIL1</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_UTIL1 = createField("AM_FLG_ITU_UTIL1", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_UTIL2</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_UTIL2 = createField("AM_FLG_ITU_UTIL2", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FINAL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FINAL = createField("AM_FLG_FINAL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_AFF_REG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_AFF_REG = createField("AM_FLG_AFF_REG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FINAL_ITU</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FINAL_ITU = createField("AM_FLG_FINAL_ITU", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_AFF_ITU</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_AFF_ITU = createField("AM_FLG_AFF_ITU", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_MISC_1</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_MISC_1 = createField("AM_FLG_MISC_1", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_RECLASSIFY</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_RECLASSIFY = createField("AM_FLG_RECLASSIFY", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_LOP</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_LOP = createField("AM_FLG_LOP", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PTOGEN_IMG</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PTOGEN_IMG = createField("AM_FLG_PTOGEN_IMG", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_IN_LOC_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_IN_LOC_DT = createField("AM_IN_LOC_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LOS_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_LOS_DT = createField("AM_LOS_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_1_ACTN_CT_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_1_ACTN_CT_DT = createField("AM_1_ACTN_CT_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LAST_ACTN_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_LAST_ACTN_DT = createField("AM_LAST_ACTN_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LAST_RSP_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_LAST_RSP_DT = createField("AM_LAST_RSP_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_STAT_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_STAT_DT = createField("AM_STAT_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_1_PARA_CT_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_1_PARA_CT_DT = createField("AM_1_PARA_CT_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_OPPS_CMPLT_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_OPPS_CMPLT_DT = createField("AM_OPPS_CMPLT_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_USE_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_USE_FIL = createField("AM_FLG_USE_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_USE_AMED</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_USE_AMED = createField("AM_FLG_USE_AMED", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_USE_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_USE_CUR = createField("AM_FLG_USE_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_44D_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_44D_FIL = createField("AM_FLG_44D_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_44D_AMED</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_44D_AMED = createField("AM_FLG_44D_AMED", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_44D_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_44D_CUR = createField("AM_FLG_44D_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_44E_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_44E_FIL = createField("AM_FLG_44E_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_44E_AMED</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_44E_AMED = createField("AM_FLG_44E_AMED", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_44E_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_44E_CUR = createField("AM_FLG_44E_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NO_BAS_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NO_BAS_FIL = createField("AM_FLG_NO_BAS_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NO_BAS_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NO_BAS_CUR = createField("AM_FLG_NO_BAS_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FRP_DT_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FRP_DT_FIL = createField("AM_FLG_FRP_DT_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FR_CRT_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FR_CRT_FIL = createField("AM_FLG_FR_CRT_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SPEC_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SPEC_FIL = createField("AM_FLG_SPEC_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_USE_DT_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_USE_DT_FIL = createField("AM_FLG_USE_DT_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_C_DRW_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_C_DRW_FIL = createField("AM_FLG_C_DRW_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_C_DRW_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_C_DRW_CUR = createField("AM_FLG_C_DRW_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_3D_DRW_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_3D_DRW_FIL = createField("AM_FLG_3D_DRW_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_3D_DRW_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_3D_DRW_CUR = createField("AM_FLG_3D_DRW_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_B_SPEC_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_B_SPEC_FIL = createField("AM_FLG_B_SPEC_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_B_SPEC_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_B_SPEC_CUR = createField("AM_FLG_B_SPEC_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_2_ACT_CT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_2_ACT_CT = createField("AM_FLG_2_ACT_CT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ITU_AMED</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ITU_AMED = createField("AM_FLG_ITU_AMED", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_DKT_CARD_T</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_DKT_CARD_T = createField("AM_FLG_DKT_CARD_T", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_IN_TICRS</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_IN_TICRS = createField("AM_FLG_IN_TICRS", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TTAB_RQST</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TTAB_RQST = createField("AM_FLG_TTAB_RQST", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_DOCK</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_DOCK = createField("AM_DT_DOCK", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_66A_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_66A_CUR = createField("AM_FLG_66A_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_66A_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_66A_FIL = createField("AM_FLG_66A_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_STD_CHAR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_STD_CHAR = createField("AM_FLG_STD_CHAR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TEASPL_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TEASPL_FIL = createField("AM_FLG_TEASPL_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TEASPL_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TEASPL_CUR = createField("AM_FLG_TEASPL_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LIE_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_LIE_NUM = createField("AM_LIE_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_PHYC_LOC</code>.
     */
    public final TableField<TramAmRecord, String> AM_PHYC_LOC = createField("AM_PHYC_LOC", org.jooq.impl.SQLDataType.VARCHAR.length(5).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_PHYC_LOC_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_PHYC_LOC_DT = createField("AM_PHYC_LOC_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_PHYC_LOC_TI</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_PHYC_LOC_TI = createField("AM_PHYC_LOC_TI", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ITU_EMPE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_ITU_EMPE = createField("AM_ITU_EMPE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_PET_EMPE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_PET_EMPE = createField("AM_PET_EMPE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LIE_ASGN_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_LIE_ASGN_DT = createField("AM_LIE_ASGN_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_INCOM_CORR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_INCOM_CORR = createField("AM_FLG_INCOM_CORR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_FA_PUB</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_FA_PUB = createField("AM_FLG_FA_PUB", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_INCOM_CORR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_INCOM_CORR = createField("AM_DT_INCOM_CORR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_SUSP_CHECK</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_SUSP_CHECK = createField("AM_DT_SUSP_CHECK", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LIE_UNIT</code>.
     */
    public final TableField<TramAmRecord, String> AM_LIE_UNIT = createField("AM_LIE_UNIT", org.jooq.impl.SQLDataType.VARCHAR.length(3).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_LAST_EVENT</code>.
     */
    public final TableField<TramAmRecord, String> AM_LAST_EVENT = createField("AM_LAST_EVENT", org.jooq.impl.SQLDataType.VARCHAR.length(5).defaultValue(org.jooq.impl.DSL.inline(" ", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOAM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOAM = createField("AM_FLG_NOAM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_INCOM_C_ITU</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_INCOM_C_ITU = createField("AM_DT_INCOM_C_ITU", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_ASGN_ITU</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_ASGN_ITU = createField("AM_DT_ASGN_ITU", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_JNOTE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_JNOTE = createField("AM_FLG_JNOTE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_POTL_ABAN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_POTL_ABAN = createField("AM_DT_POTL_ABAN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_ASGN_PET</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_ASGN_PET = createField("AM_DT_ASGN_PET", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PET</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PET = createField("AM_FLG_PET", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NWAP_OFF</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NWAP_OFF = createField("AM_FLG_NWAP_OFF", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_EMAIL_AUTH</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_EMAIL_AUTH = createField("AM_FLG_EMAIL_AUTH", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ACCEL_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ACCEL_CUR = createField("AM_FLG_ACCEL_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_ACCEL_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_ACCEL_FIL = createField("AM_FLG_ACCEL_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NA_XSEARCH</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NA_XSEARCH = createField("AM_FLG_NA_XSEARCH", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NEW_APPL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NEW_APPL = createField("AM_FLG_NEW_APPL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_INCOM_C_NR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_INCOM_C_NR = createField("AM_DT_INCOM_C_NR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_INCOM_C_PR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_INCOM_C_PR = createField("AM_DT_INCOM_C_PR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_ASGN_PR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_ASGN_PR = createField("AM_DT_ASGN_PR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_71_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_71_FIL = createField("AM_FLG_SCT_71_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_71_AX</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_71_AX = createField("AM_FLG_SCT_71_AX", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_SCT_71_P_A</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_SCT_71_P_A = createField("AM_FLG_SCT_71_P_A", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PRLM_AMND</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PRLM_AMND = createField("AM_FLG_PRLM_AMND", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_INCOM_C_TQR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_INCOM_C_TQR = createField("AM_DT_INCOM_C_TQR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_TQR_EMPE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_TQR_EMPE = createField("AM_TQR_EMPE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DT_ASGN_TQR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DT_ASGN_TQR = createField("AM_DT_ASGN_TQR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_HOLD_EMPE</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_HOLD_EMPE = createField("AM_HOLD_EMPE", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_HOLD_DT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_HOLD_DT = createField("AM_HOLD_DT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DEADQ_STAT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DEADQ_STAT = createField("AM_DEADQ_STAT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DEADQ_DT_INCOM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DEADQ_DT_INCOM = createField("AM_DEADQ_DT_INCOM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_DEADQ_EMP_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_DEADQ_EMP_NUM = createField("AM_DEADQ_EMP_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_PROTEST_LTR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_PROTEST_LTR = createField("AM_FLG_PROTEST_LTR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TEASRF_FIL</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TEASRF_FIL = createField("AM_FLG_TEASRF_FIL", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_TEASRF_CUR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_TEASRF_CUR = createField("AM_FLG_TEASRF_CUR", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ABANQ_STAT</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_ABANQ_STAT = createField("AM_ABANQ_STAT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ABANQ_DT_INCOM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_ABANQ_DT_INCOM = createField("AM_ABANQ_DT_INCOM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_ABANQ_EMP_NUM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_ABANQ_EMP_NUM = createField("AM_ABANQ_EMP_NUM", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_RSN</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_RSN = createField("AM_RSN", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_MARK_DESC</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_MARK_DESC = createField("AM_FLG_MARK_DESC", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_FLG_NOT_ELEC</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_FLG_NOT_ELEC = createField("AM_FLG_NOT_ELEC", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_BAR_MEM_YR</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_BAR_MEM_YR = createField("AM_BAR_MEM_YR", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_BAR_MEM_MM</code>.
     */
    public final TableField<TramAmRecord, Integer> AM_BAR_MEM_MM = createField("AM_BAR_MEM_MM", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_BAR_MEM_STATE</code>.
     */
    public final TableField<TramAmRecord, String> AM_BAR_MEM_STATE = createField("AM_BAR_MEM_STATE", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

    /**
     * The column <code>DQTRAM.TRAM_AM.AM_BAR_MEM</code>.
     */
    public final TableField<TramAmRecord, String> AM_BAR_MEM = createField("AM_BAR_MEM", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

    /**
     * Create a <code>DQTRAM.TRAM_AM</code> table reference
     */
    public TramAm() {
        this("TRAM_AM", null);
    }

    /**
     * Create an aliased <code>DQTRAM.TRAM_AM</code> table reference
     */
    public TramAm(String alias) {
        this(alias, TRAM_AM);
    }

    private TramAm(String alias, Table<TramAmRecord> aliased) {
        this(alias, aliased, null);
    }

    private TramAm(String alias, Table<TramAmRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtram.DQTRAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TramAm as(String alias) {
        return new TramAm(alias, this);
    }

    /**
     * Rename this table
     */
    public TramAm rename(String name) {
        return new TramAm(name, null);
    }
}
