/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model;


import com.dq.DQTRM.model.tables.TmAdditionalStatement;
import com.dq.DQTRM.model.tables.TmAmendment;
import com.dq.DQTRM.model.tables.TmDesignElement;
import com.dq.DQTRM.model.tables.TmDrawing;
import com.dq.DQTRM.model.tables.TmEmployeeAssignment;
import com.dq.DQTRM.model.tables.TmMarkType;
import com.dq.DQTRM.model.tables.TmPriorRegistration;
import com.dq.DQTRM.model.tables.TmPublication;
import com.dq.DQTRM.model.tables.TmRelationship;
import com.dq.DQTRM.model.tables.TmRenewal;
import com.dq.DQTRM.model.tables.Trademark;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dqtrm extends SchemaImpl {

    private static final long serialVersionUID = 104373571;

    /**
     * The reference instance of <code>DQTRM</code>
     */
    public static final Dqtrm DQTRM = new Dqtrm();

    /**
     * The table <code>DQTRM.TM_ADDITIONAL_STATEMENT</code>.
     */
    public final TmAdditionalStatement TM_ADDITIONAL_STATEMENT = com.dq.DQTRM.model.tables.TmAdditionalStatement.TM_ADDITIONAL_STATEMENT;

    /**
     * The table <code>DQTRM.TM_AMENDMENT</code>.
     */
    public final TmAmendment TM_AMENDMENT = com.dq.DQTRM.model.tables.TmAmendment.TM_AMENDMENT;

    /**
     * The table <code>DQTRM.TM_DESIGN_ELEMENT</code>.
     */
    public final TmDesignElement TM_DESIGN_ELEMENT = com.dq.DQTRM.model.tables.TmDesignElement.TM_DESIGN_ELEMENT;

    /**
     * The table <code>DQTRM.TM_DRAWING</code>.
     */
    public final TmDrawing TM_DRAWING = com.dq.DQTRM.model.tables.TmDrawing.TM_DRAWING;

    /**
     * The table <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT</code>.
     */
    public final TmEmployeeAssignment TM_EMPLOYEE_ASSIGNMENT = com.dq.DQTRM.model.tables.TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT;

    /**
     * The table <code>DQTRM.TM_MARK_TYPE</code>.
     */
    public final TmMarkType TM_MARK_TYPE = com.dq.DQTRM.model.tables.TmMarkType.TM_MARK_TYPE;

    /**
     * The table <code>DQTRM.TM_PRIOR_REGISTRATION</code>.
     */
    public final TmPriorRegistration TM_PRIOR_REGISTRATION = com.dq.DQTRM.model.tables.TmPriorRegistration.TM_PRIOR_REGISTRATION;

    /**
     * The table <code>DQTRM.TM_PUBLICATION</code>.
     */
    public final TmPublication TM_PUBLICATION = com.dq.DQTRM.model.tables.TmPublication.TM_PUBLICATION;

    /**
     * The table <code>DQTRM.TM_RELATIONSHIP</code>.
     */
    public final TmRelationship TM_RELATIONSHIP = com.dq.DQTRM.model.tables.TmRelationship.TM_RELATIONSHIP;

    /**
     * The table <code>DQTRM.TM_RENEWAL</code>.
     */
    public final TmRenewal TM_RENEWAL = com.dq.DQTRM.model.tables.TmRenewal.TM_RENEWAL;

    /**
     * The table <code>DQTRM.TRADEMARK</code>.
     */
    public final Trademark TRADEMARK = com.dq.DQTRM.model.tables.Trademark.TRADEMARK;

    /**
     * No further instances allowed
     */
    private Dqtrm() {
        super("DQTRM", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TmAdditionalStatement.TM_ADDITIONAL_STATEMENT,
            TmAmendment.TM_AMENDMENT,
            TmDesignElement.TM_DESIGN_ELEMENT,
            TmDrawing.TM_DRAWING,
            TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT,
            TmMarkType.TM_MARK_TYPE,
            TmPriorRegistration.TM_PRIOR_REGISTRATION,
            TmPublication.TM_PUBLICATION,
            TmRelationship.TM_RELATIONSHIP,
            TmRenewal.TM_RENEWAL,
            Trademark.TRADEMARK);
    }
}
