/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model;


import com.dq.DQTRM.model.tables.TmAdditionalStatement;
import com.dq.DQTRM.model.tables.TmAmendment;
import com.dq.DQTRM.model.tables.TmDesignElement;
import com.dq.DQTRM.model.tables.TmDrawing;
import com.dq.DQTRM.model.tables.TmEmployeeAssignment;
import com.dq.DQTRM.model.tables.TmMarkType;
import com.dq.DQTRM.model.tables.TmPriorRegistration;
import com.dq.DQTRM.model.tables.TmPublication;
import com.dq.DQTRM.model.tables.TmRelationship;
import com.dq.DQTRM.model.tables.TmRenewal;
import com.dq.DQTRM.model.tables.Trademark;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in DQTRM
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DQTRM.TM_ADDITIONAL_STATEMENT</code>.
     */
    public static final TmAdditionalStatement TM_ADDITIONAL_STATEMENT = com.dq.DQTRM.model.tables.TmAdditionalStatement.TM_ADDITIONAL_STATEMENT;

    /**
     * The table <code>DQTRM.TM_AMENDMENT</code>.
     */
    public static final TmAmendment TM_AMENDMENT = com.dq.DQTRM.model.tables.TmAmendment.TM_AMENDMENT;

    /**
     * The table <code>DQTRM.TM_DESIGN_ELEMENT</code>.
     */
    public static final TmDesignElement TM_DESIGN_ELEMENT = com.dq.DQTRM.model.tables.TmDesignElement.TM_DESIGN_ELEMENT;

    /**
     * The table <code>DQTRM.TM_DRAWING</code>.
     */
    public static final TmDrawing TM_DRAWING = com.dq.DQTRM.model.tables.TmDrawing.TM_DRAWING;

    /**
     * The table <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT</code>.
     */
    public static final TmEmployeeAssignment TM_EMPLOYEE_ASSIGNMENT = com.dq.DQTRM.model.tables.TmEmployeeAssignment.TM_EMPLOYEE_ASSIGNMENT;

    /**
     * The table <code>DQTRM.TM_MARK_TYPE</code>.
     */
    public static final TmMarkType TM_MARK_TYPE = com.dq.DQTRM.model.tables.TmMarkType.TM_MARK_TYPE;

    /**
     * The table <code>DQTRM.TM_PRIOR_REGISTRATION</code>.
     */
    public static final TmPriorRegistration TM_PRIOR_REGISTRATION = com.dq.DQTRM.model.tables.TmPriorRegistration.TM_PRIOR_REGISTRATION;

    /**
     * The table <code>DQTRM.TM_PUBLICATION</code>.
     */
    public static final TmPublication TM_PUBLICATION = com.dq.DQTRM.model.tables.TmPublication.TM_PUBLICATION;

    /**
     * The table <code>DQTRM.TM_RELATIONSHIP</code>.
     */
    public static final TmRelationship TM_RELATIONSHIP = com.dq.DQTRM.model.tables.TmRelationship.TM_RELATIONSHIP;

    /**
     * The table <code>DQTRM.TM_RENEWAL</code>.
     */
    public static final TmRenewal TM_RENEWAL = com.dq.DQTRM.model.tables.TmRenewal.TM_RENEWAL;

    /**
     * The table <code>DQTRM.TRADEMARK</code>.
     */
    public static final Trademark TRADEMARK = com.dq.DQTRM.model.tables.Trademark.TRADEMARK;
}
