/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmAdditionalStatementRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmAdditionalStatement extends TableImpl<TmAdditionalStatementRecord> {

    private static final long serialVersionUID = -2115440401;

    /**
     * The reference instance of <code>DQTRM.TM_ADDITIONAL_STATEMENT</code>
     */
    public static final TmAdditionalStatement TM_ADDITIONAL_STATEMENT = new TmAdditionalStatement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmAdditionalStatementRecord> getRecordType() {
        return TmAdditionalStatementRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.FK_TRADEMARK_GID</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> FK_TRADEMARK_GID = createField("FK_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.FK_STATEMENT_TYPE_CD</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> FK_STATEMENT_TYPE_CD = createField("FK_STATEMENT_TYPE_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.ORDER_NO</code>.
     */
    public final TableField<TmAdditionalStatementRecord, Integer> ORDER_NO = createField("ORDER_NO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmAdditionalStatementRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.CREATE_TS</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.CREATE_USER_ID</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.LAST_MOD_TS</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_ADDITIONAL_STATEMENT.STATEMENT_TX</code>.
     */
    public final TableField<TmAdditionalStatementRecord, String> STATEMENT_TX = createField("STATEMENT_TX", org.jooq.impl.SQLDataType.VARCHAR.length(32767).nullable(false), this, "");

    /**
     * Create a <code>DQTRM.TM_ADDITIONAL_STATEMENT</code> table reference
     */
    public TmAdditionalStatement() {
        this("TM_ADDITIONAL_STATEMENT", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_ADDITIONAL_STATEMENT</code> table reference
     */
    public TmAdditionalStatement(String alias) {
        this(alias, TM_ADDITIONAL_STATEMENT);
    }

    private TmAdditionalStatement(String alias, Table<TmAdditionalStatementRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmAdditionalStatement(String alias, Table<TmAdditionalStatementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmAdditionalStatement as(String alias) {
        return new TmAdditionalStatement(alias, this);
    }

    /**
     * Rename this table
     */
    public TmAdditionalStatement rename(String name) {
        return new TmAdditionalStatement(name, null);
    }
}
