/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmDesignElementRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmDesignElement extends TableImpl<TmDesignElementRecord> {

    private static final long serialVersionUID = -1015693820;

    /**
     * The reference instance of <code>DQTRM.TM_DESIGN_ELEMENT</code>
     */
    public static final TmDesignElement TM_DESIGN_ELEMENT = new TmDesignElement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmDesignElementRecord> getRecordType() {
        return TmDesignElementRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.FK_TRADEMARK_GID</code>.
     */
    public final TableField<TmDesignElementRecord, String> FK_TRADEMARK_GID = createField("FK_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.FK_DESIGN_SEARCH_GROUP_CD</code>.
     */
    public final TableField<TmDesignElementRecord, String> FK_DESIGN_SEARCH_GROUP_CD = createField("FK_DESIGN_SEARCH_GROUP_CD", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmDesignElementRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.CREATE_TS</code>.
     */
    public final TableField<TmDesignElementRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.CREATE_USER_ID</code>.
     */
    public final TableField<TmDesignElementRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.LAST_MOD_TS</code>.
     */
    public final TableField<TmDesignElementRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TM_DESIGN_ELEMENT.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmDesignElementRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * Create a <code>DQTRM.TM_DESIGN_ELEMENT</code> table reference
     */
    public TmDesignElement() {
        this("TM_DESIGN_ELEMENT", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_DESIGN_ELEMENT</code> table reference
     */
    public TmDesignElement(String alias) {
        this(alias, TM_DESIGN_ELEMENT);
    }

    private TmDesignElement(String alias, Table<TmDesignElementRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmDesignElement(String alias, Table<TmDesignElementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmDesignElement as(String alias) {
        return new TmDesignElement(alias, this);
    }

    /**
     * Rename this table
     */
    public TmDesignElement rename(String name) {
        return new TmDesignElement(name, null);
    }
}
