/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmEmployeeAssignmentRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmEmployeeAssignment extends TableImpl<TmEmployeeAssignmentRecord> {

    private static final long serialVersionUID = 857602192;

    /**
     * The reference instance of <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT</code>
     */
    public static final TmEmployeeAssignment TM_EMPLOYEE_ASSIGNMENT = new TmEmployeeAssignment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmEmployeeAssignmentRecord> getRecordType() {
        return TmEmployeeAssignmentRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.FK_TRADEMARK_GID</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> FK_TRADEMARK_GID = createField("FK_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.FK_TM_EMPLOYEE_ROLE_CD</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> FK_TM_EMPLOYEE_ROLE_CD = createField("FK_TM_EMPLOYEE_ROLE_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CFK_EMPLOYEE_NO</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> CFK_EMPLOYEE_NO = createField("CFK_EMPLOYEE_NO", org.jooq.impl.SQLDataType.VARCHAR.length(6).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CREATE_TS</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.CREATE_USER_ID</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_TS</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT.EFFECTIVE_DT</code>.
     */
    public final TableField<TmEmployeeAssignmentRecord, String> EFFECTIVE_DT = createField("EFFECTIVE_DT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT</code> table reference
     */
    public TmEmployeeAssignment() {
        this("TM_EMPLOYEE_ASSIGNMENT", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_EMPLOYEE_ASSIGNMENT</code> table reference
     */
    public TmEmployeeAssignment(String alias) {
        this(alias, TM_EMPLOYEE_ASSIGNMENT);
    }

    private TmEmployeeAssignment(String alias, Table<TmEmployeeAssignmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmEmployeeAssignment(String alias, Table<TmEmployeeAssignmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmEmployeeAssignment as(String alias) {
        return new TmEmployeeAssignment(alias, this);
    }

    /**
     * Rename this table
     */
    public TmEmployeeAssignment rename(String name) {
        return new TmEmployeeAssignment(name, null);
    }
}
