/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmMarkTypeRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmMarkType extends TableImpl<TmMarkTypeRecord> {

    private static final long serialVersionUID = 2043130689;

    /**
     * The reference instance of <code>DQTRM.TM_MARK_TYPE</code>
     */
    public static final TmMarkType TM_MARK_TYPE = new TmMarkType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmMarkTypeRecord> getRecordType() {
        return TmMarkTypeRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.FK_TRADEMARK_GID</code>.
     */
    public final TableField<TmMarkTypeRecord, String> FK_TRADEMARK_GID = createField("FK_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.FK_MARK_TYPE_CD</code>.
     */
    public final TableField<TmMarkTypeRecord, String> FK_MARK_TYPE_CD = createField("FK_MARK_TYPE_CD", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmMarkTypeRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.CREATE_TS</code>.
     */
    public final TableField<TmMarkTypeRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.CREATE_USER_ID</code>.
     */
    public final TableField<TmMarkTypeRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.LAST_MOD_TS</code>.
     */
    public final TableField<TmMarkTypeRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_MARK_TYPE.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmMarkTypeRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * Create a <code>DQTRM.TM_MARK_TYPE</code> table reference
     */
    public TmMarkType() {
        this("TM_MARK_TYPE", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_MARK_TYPE</code> table reference
     */
    public TmMarkType(String alias) {
        this(alias, TM_MARK_TYPE);
    }

    private TmMarkType(String alias, Table<TmMarkTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmMarkType(String alias, Table<TmMarkTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmMarkType as(String alias) {
        return new TmMarkType(alias, this);
    }

    /**
     * Rename this table
     */
    public TmMarkType rename(String name) {
        return new TmMarkType(name, null);
    }
}
