/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmPublicationRecord;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmPublication extends TableImpl<TmPublicationRecord> {

    private static final long serialVersionUID = 1356249788;

    /**
     * The reference instance of <code>DQTRM.TM_PUBLICATION</code>
     */
    public static final TmPublication TM_PUBLICATION = new TmPublication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmPublicationRecord> getRecordType() {
        return TmPublicationRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_PUBLICATION.FK_TRADEMARK_GID</code>.
     */
    public final TableField<TmPublicationRecord, String> FK_TRADEMARK_GID = createField("FK_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.TM_PUBLICATION_GID</code>.
     */
    public final TableField<TmPublicationRecord, String> TM_PUBLICATION_GID = createField("TM_PUBLICATION_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.ELIGIBLE_TS</code>.
     */
    public final TableField<TmPublicationRecord, String> ELIGIBLE_TS = createField("ELIGIBLE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.OG_ACTION_DT</code>.
     */
    public final TableField<TmPublicationRecord, Date> OG_ACTION_DT = createField("OG_ACTION_DT", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.LEGACY_OG_STATUS_CD</code>.
     */
    public final TableField<TmPublicationRecord, String> LEGACY_OG_STATUS_CD = createField("LEGACY_OG_STATUS_CD", org.jooq.impl.SQLDataType.VARCHAR.length(4).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmPublicationRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.CREATE_TS</code>.
     */
    public final TableField<TmPublicationRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.CREATE_USER_ID</code>.
     */
    public final TableField<TmPublicationRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.LAST_MOD_TS</code>.
     */
    public final TableField<TmPublicationRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmPublicationRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_PUBLICATION.PRINT_MARK_DESCRIPTION_IN</code>.
     */
    public final TableField<TmPublicationRecord, String> PRINT_MARK_DESCRIPTION_IN = createField("PRINT_MARK_DESCRIPTION_IN", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false).defaultValue(org.jooq.impl.DSL.inline("N", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>DQTRM.TM_PUBLICATION</code> table reference
     */
    public TmPublication() {
        this("TM_PUBLICATION", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_PUBLICATION</code> table reference
     */
    public TmPublication(String alias) {
        this(alias, TM_PUBLICATION);
    }

    private TmPublication(String alias, Table<TmPublicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmPublication(String alias, Table<TmPublicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmPublication as(String alias) {
        return new TmPublication(alias, this);
    }

    /**
     * Rename this table
     */
    public TmPublication rename(String name) {
        return new TmPublication(name, null);
    }
}
