/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmRelationshipRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmRelationship extends TableImpl<TmRelationshipRecord> {

    private static final long serialVersionUID = -2130576770;

    /**
     * The reference instance of <code>DQTRM.TM_RELATIONSHIP</code>
     */
    public static final TmRelationship TM_RELATIONSHIP = new TmRelationship();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmRelationshipRecord> getRecordType() {
        return TmRelationshipRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.FK_PARENT_TRADEMARK_GID</code>.
     */
    public final TableField<TmRelationshipRecord, String> FK_PARENT_TRADEMARK_GID = createField("FK_PARENT_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.FK_RELATED_TRADEMARK_GID</code>.
     */
    public final TableField<TmRelationshipRecord, String> FK_RELATED_TRADEMARK_GID = createField("FK_RELATED_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.FK_RELATIONSHIP_TYPE_CD</code>.
     */
    public final TableField<TmRelationshipRecord, String> FK_RELATIONSHIP_TYPE_CD = createField("FK_RELATIONSHIP_TYPE_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmRelationshipRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.CREATE_TS</code>.
     */
    public final TableField<TmRelationshipRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.CREATE_USER_ID</code>.
     */
    public final TableField<TmRelationshipRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.LAST_MOD_TS</code>.
     */
    public final TableField<TmRelationshipRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TM_RELATIONSHIP.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmRelationshipRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * Create a <code>DQTRM.TM_RELATIONSHIP</code> table reference
     */
    public TmRelationship() {
        this("TM_RELATIONSHIP", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_RELATIONSHIP</code> table reference
     */
    public TmRelationship(String alias) {
        this(alias, TM_RELATIONSHIP);
    }

    private TmRelationship(String alias, Table<TmRelationshipRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmRelationship(String alias, Table<TmRelationshipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRelationship as(String alias) {
        return new TmRelationship(alias, this);
    }

    /**
     * Rename this table
     */
    public TmRelationship rename(String name) {
        return new TmRelationship(name, null);
    }
}
