/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TmRenewalRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TmRenewal extends TableImpl<TmRenewalRecord> {

    private static final long serialVersionUID = -1118443872;

    /**
     * The reference instance of <code>DQTRM.TM_RENEWAL</code>
     */
    public static final TmRenewal TM_RENEWAL = new TmRenewal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TmRenewalRecord> getRecordType() {
        return TmRenewalRecord.class;
    }

    /**
     * The column <code>DQTRM.TM_RENEWAL.FK_TRADEMARK_GID</code>.
     */
    public final TableField<TmRenewalRecord, String> FK_TRADEMARK_GID = createField("FK_TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.SEQUENCE_NO</code>.
     */
    public final TableField<TmRenewalRecord, Integer> SEQUENCE_NO = createField("SEQUENCE_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.RENEWAL_FILED_DT</code>.
     */
    public final TableField<TmRenewalRecord, String> RENEWAL_FILED_DT = createField("RENEWAL_FILED_DT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.RENEWAL_BEGIN_EFFECTIVE_DT</code>.
     */
    public final TableField<TmRenewalRecord, String> RENEWAL_BEGIN_EFFECTIVE_DT = createField("RENEWAL_BEGIN_EFFECTIVE_DT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.RENEWAL_END_EFFECTIVE_DT</code>.
     */
    public final TableField<TmRenewalRecord, String> RENEWAL_END_EFFECTIVE_DT = createField("RENEWAL_END_EFFECTIVE_DT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TmRenewalRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.CREATE_TS</code>.
     */
    public final TableField<TmRenewalRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.CREATE_USER_ID</code>.
     */
    public final TableField<TmRenewalRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.LAST_MOD_TS</code>.
     */
    public final TableField<TmRenewalRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TM_RENEWAL.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TmRenewalRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * Create a <code>DQTRM.TM_RENEWAL</code> table reference
     */
    public TmRenewal() {
        this("TM_RENEWAL", null);
    }

    /**
     * Create an aliased <code>DQTRM.TM_RENEWAL</code> table reference
     */
    public TmRenewal(String alias) {
        this(alias, TM_RENEWAL);
    }

    private TmRenewal(String alias, Table<TmRenewalRecord> aliased) {
        this(alias, aliased, null);
    }

    private TmRenewal(String alias, Table<TmRenewalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TmRenewal as(String alias) {
        return new TmRenewal(alias, this);
    }

    /**
     * Rename this table
     */
    public TmRenewal rename(String name) {
        return new TmRenewal(name, null);
    }
}
