/**
 * This class is generated by jOOQ
 */
package com.dq.DQTRM.model.tables;


import com.dq.DQTRM.model.Dqtrm;
import com.dq.DQTRM.model.tables.records.TrademarkRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trademark extends TableImpl<TrademarkRecord> {

    private static final long serialVersionUID = 1931594623;

    /**
     * The reference instance of <code>DQTRM.TRADEMARK</code>
     */
    public static final Trademark TRADEMARK = new Trademark();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrademarkRecord> getRecordType() {
        return TrademarkRecord.class;
    }

    /**
     * The column <code>DQTRM.TRADEMARK.TRADEMARK_GID</code>.
     */
    public final TableField<TrademarkRecord, String> TRADEMARK_GID = createField("TRADEMARK_GID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.FK_MARK_DRAWING_TYPE_CD</code>.
     */
    public final TableField<TrademarkRecord, String> FK_MARK_DRAWING_TYPE_CD = createField("FK_MARK_DRAWING_TYPE_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.FK_FEE_PROCESS_TYPE_CD</code>.
     */
    public final TableField<TrademarkRecord, String> FK_FEE_PROCESS_TYPE_CD = createField("FK_FEE_PROCESS_TYPE_CD", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.SERIAL_NUM_TX</code>.
     */
    public final TableField<TrademarkRecord, String> SERIAL_NUM_TX = createField("SERIAL_NUM_TX", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.REGISTRATION_NUM</code>.
     */
    public final TableField<TrademarkRecord, Integer> REGISTRATION_NUM = createField("REGISTRATION_NUM", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.FILING_DT</code>.
     */
    public final TableField<TrademarkRecord, String> FILING_DT = createField("FILING_DT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.REGISTRY_CT</code>.
     */
    public final TableField<TrademarkRecord, String> REGISTRY_CT = createField("REGISTRY_CT", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.STANDARD_CHARACTER_TX</code>.
     */
    public final TableField<TrademarkRecord, String> STANDARD_CHARACTER_TX = createField("STANDARD_CHARACTER_TX", org.jooq.impl.SQLDataType.VARCHAR.length(32767), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.MARK_DESCRIPTION_TX</code>.
     */
    public final TableField<TrademarkRecord, String> MARK_DESCRIPTION_TX = createField("MARK_DESCRIPTION_TX", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.PREFERRED_CONTACT_METHOD_CT</code>.
     */
    public final TableField<TrademarkRecord, String> PREFERRED_CONTACT_METHOD_CT = createField("PREFERRED_CONTACT_METHOD_CT", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.EFFECTIVE_FILING_DT</code>.
     */
    public final TableField<TrademarkRecord, String> EFFECTIVE_FILING_DT = createField("EFFECTIVE_FILING_DT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.COLLECTIVE_IN</code>.
     */
    public final TableField<TrademarkRecord, String> COLLECTIVE_IN = createField("COLLECTIVE_IN", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false).defaultValue(org.jooq.impl.DSL.inline("N", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.LEGACY_STATUS_CD</code>.
     */
    public final TableField<TrademarkRecord, Integer> LEGACY_STATUS_CD = createField("LEGACY_STATUS_CD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.LOCK_CONTROL_NO</code>.
     */
    public final TableField<TrademarkRecord, Integer> LOCK_CONTROL_NO = createField("LOCK_CONTROL_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.CREATE_TS</code>.
     */
    public final TableField<TrademarkRecord, String> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.CREATE_USER_ID</code>.
     */
    public final TableField<TrademarkRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.LAST_MOD_TS</code>.
     */
    public final TableField<TrademarkRecord, String> LAST_MOD_TS = createField("LAST_MOD_TS", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.LAST_MOD_USER_ID</code>.
     */
    public final TableField<TrademarkRecord, String> LAST_MOD_USER_ID = createField("LAST_MOD_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.STATUS_DT</code>.
     */
    public final TableField<TrademarkRecord, String> STATUS_DT = createField("STATUS_DT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.LAST_ACTION_DT</code>.
     */
    public final TableField<TrademarkRecord, String> LAST_ACTION_DT = createField("LAST_ACTION_DT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>DQTRM.TRADEMARK.AVAILABLE_FOR_SOU_IN</code>.
     */
    public final TableField<TrademarkRecord, String> AVAILABLE_FOR_SOU_IN = createField("AVAILABLE_FOR_SOU_IN", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false).defaultValue(org.jooq.impl.DSL.inline("N", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>DQTRM.TRADEMARK</code> table reference
     */
    public Trademark() {
        this("TRADEMARK", null);
    }

    /**
     * Create an aliased <code>DQTRM.TRADEMARK</code> table reference
     */
    public Trademark(String alias) {
        this(alias, TRADEMARK);
    }

    private Trademark(String alias, Table<TrademarkRecord> aliased) {
        this(alias, aliased, null);
    }

    private Trademark(String alias, Table<TrademarkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dqtrm.DQTRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Trademark as(String alias) {
        return new Trademark(alias, this);
    }

    /**
     * Rename this table
     */
    public Trademark rename(String name) {
        return new Trademark(name, null);
    }
}
